AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The fortune serverless app
Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
Resources:
  GetSomeFortuneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: somefortune/
      Handler: somefortune
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /some
            Method: GET
Outputs:
  FortuneAPIEndpoint:
    Description: "Fortune HTTP API Gateway endpoint URL for Prod env"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

